FIX: yaml syntax error

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,14 +16,14 @@ jobs:
         steps:
             - uses: actions/checkout@v3
             - id: check_repository_cleanliness
-                run: |
-                    TRASH_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "#*#" -or -iname "*pain_au_chocolat*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*.gcov")
-                    for FILES in $TRASH_FILES; do
-                        echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
-                    done
-                    if [ -n "$TRASH_FILES"]; then
-                        exit 1
-                    fi
+            run: |
+                TRASH_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "#*#" -or -iname "*pain_au_chocolat*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*.gcov")
+                for FILES in $TRASH_FILES; do
+                    echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
+                done
+                if [ -n "$TRASH_FILES"]; then
+                    exit 1
+                fi
     check_if_compil:
         needs: [check_repo]
         name: "check if the make compil"
